basePath: /
definitions:
  dto.CreateOrderItemRequest:
    properties:
      price:
        minimum: 0
        type: number
      product_id:
        minimum: 1
        type: integer
      quantity:
        minimum: 1
        type: integer
    required:
    - price
    - product_id
    - quantity
    type: object
  dto.CreateOrderRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/dto.CreateOrderItemRequest'
        minItems: 1
        type: array
      user_id:
        minimum: 1
        type: integer
    required:
    - items
    - user_id
    type: object
  dto.CreatePaymentRequest:
    properties:
      amount_cents:
        type: integer
      currency:
        type: string
      order_id:
        type: integer
    type: object
  dto.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  dto.GetJWTRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.GetJWTResponse:
    properties:
      access_token:
        type: string
    type: object
  dto.OrderDTO:
    properties:
      created_at:
        type: string
      currency:
        type: string
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/dto.OrderItemDTO'
        type: array
      payments:
        items:
          $ref: '#/definitions/dto.PaymentDTO'
        type: array
      status:
        type: string
      total_price:
        type: number
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  dto.OrderItemDTO:
    properties:
      id:
        type: integer
      order_id:
        type: integer
      product:
        $ref: '#/definitions/dto.ProductDTO'
      product_id:
        type: integer
      qty:
        type: integer
      unit_price:
        type: number
    type: object
  dto.PaymentDTO:
    properties:
      amount:
        type: number
      created_at:
        type: string
      currency:
        type: string
      id:
        type: integer
      method:
        type: string
      order_id:
        type: integer
      provider:
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
  dto.ProductDTO:
    properties:
      active:
        type: boolean
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
  dto.ProductRequest:
    properties:
      active:
        type: boolean
      name:
        type: string
      price:
        type: number
    type: object
  dto.UpdateOrderItemRequest:
    properties:
      id:
        description: Optional for new items
        type: integer
      price:
        minimum: 0
        type: number
      product_id:
        minimum: 1
        type: integer
      quantity:
        minimum: 1
        type: integer
    required:
    - price
    - product_id
    - quantity
    type: object
  dto.UpdateOrderRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/dto.UpdateOrderItemRequest'
        type: array
      status:
        type: string
    type: object
  handler.Error:
    properties:
      message:
        type: string
    type: object
  model.Order:
    properties:
      created_at:
        type: string
      currency:
        type: string
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/model.OrderItem'
        type: array
      payments:
        items:
          $ref: '#/definitions/model.Payment'
        type: array
      status:
        type: string
      total_price:
        description: consider int64 cents everywhere
        type: number
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  model.OrderItem:
    properties:
      id:
        type: integer
      order_id:
        type: integer
      product:
        $ref: '#/definitions/model.Product'
      product_id:
        type: integer
      qty:
        type: integer
      unit_price:
        type: number
    type: object
  model.Payment:
    properties:
      amount_cents:
        description: Changed to int64 for Stripe compatibility
        type: integer
      created_at:
        type: string
      currency:
        type: string
      failure_code:
        type: string
      failure_reason:
        type: string
      id:
        type: integer
      method:
        type: string
      order_id:
        type: integer
      processed_at:
        type: string
      provider:
        description: e.g. "stripe"
        type: string
      status:
        description: pending, succeeded, failed, canceled
        type: string
      stripe_charge_id:
        type: string
      stripe_customer_id:
        type: string
      stripe_payment_intent_id:
        type: string
      updated_at:
        type: string
    type: object
  model.Product:
    properties:
      active:
        type: boolean
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: Christian Santos
    url: https://github.com/sancheschris
  description: Ecommerce API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ecommerce API
  version: "1.0"
paths:
  /orders:
    delete:
      consumes:
      - application/json
      description: delete order by id
      parameters:
      - description: order ID
        format: string
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Delete order
      tags:
      - orders
    get:
      consumes:
      - application/json
      description: get orders by user id
      parameters:
      - description: order ID
        format: string
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OrderDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Get orders by user id
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: Create orders
      parameters:
      - description: order request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Create order
      tags:
      - orders
  /orders/{id}:
    get:
      consumes:
      - application/json
      description: get order by id
      parameters:
      - description: order ID
        format: string
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Get order
      tags:
      - orders
    put:
      consumes:
      - application/json
      description: Update order
      parameters:
      - description: order ID
        format: string
        in: path
        name: id
        required: true
        type: string
      - description: order request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OrderDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Update order
      tags:
      - orders
  /payments:
    post:
      consumes:
      - application/json
      description: Create Payments
      parameters:
      - description: payment request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreatePaymentRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Create Payment
      tags:
      - payments
  /payments/{id}/status:
    get:
      consumes:
      - application/json
      description: get payment by status
      parameters:
      - description: payment ID
        format: string
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Get payment by status
      tags:
      - payments
  /products:
    get:
      consumes:
      - application/json
      description: get all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: List products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create products
      parameters:
      - description: product request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Create product
      tags:
      - products
  /products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete product
      parameters:
      - description: product ID
        format: string
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Delete product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Get a product
      parameters:
      - description: product ID
        format: string
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Get a product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update product
      parameters:
      - description: product ID
        format: string
        in: path
        name: id
        required: true
        type: string
      - description: product request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ProductRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Update product
      tags:
      - products
  /users:
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Create user
      tags:
      - users
  /users/generate_token:
    post:
      consumes:
      - application/json
      description: Get a user JWT
      parameters:
      - description: user credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.GetJWTRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetJWTResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Get a user JWT
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
